name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: ['latest']

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint || echo "Linting skipped"

      - name: Build
        run: bun run build

      - name: Test
        run: bun test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-bun-${{ matrix.bun-version }}
          path: dist/
          retention-days: 7
